### ISSUE TITLE
arlpy vs UnderwaterAcoustics.jl for geolocation and tomography applications

### ISSUE THREAD

**Issue by apatlpo** [org-arl/UnderwaterAcoustics.jl#26]
We are a group of researchers and engineers who have interest int underwater acoustic geolocation (analogous to LBL) and potentially tomography.
We would thus need to perform modeling in spatially (depth+range) varying environments.
For these applications what of the two packages (arlpy vs UnderwaterAcosutics.jl) would you recommend?

Some of the features (probalistic modeling, differential modeling) of UnderwaterAcosutics.jl seem interesting for our applications.
Would you confirm this point?

Julia appears (maybe wrongly) as a downside for the following reasons however:

- input preprocessing. Say we start from netcdf files containing temperature, salinity, bathymetry
- output storage. Say we want to store model outputs
- community uptake. This is an important criterium I would say. One is always afraid to contribute to a code with a small community of contributors.

Regarding point 1 and 2, I would much rather use python based code for which there are well developed librairies in order to preprocess environmental data, store data.
And arlpy would seem more appropriate to that regard.

What would you be your recommandations?

Side note: I am a physical oceanographer trying to convince my collaborators who are signal processing experts and underwater acousticians to use and contribute open and collaborative (I hope!) librairies like yours.

**Comment by mchitre** [comment]
All good questions.

The acoustic propagation modeling in `arlpy` isn't implemented in Python. Rather `arlpy` provides a Python wrapper around the well known BELLHOP Fortran code maintained by Mike Porter. This propagation model implementation is very well regarded, and supports depth and range dependence. So you should certainly be able to use `arlpy` and BELLHOP to do your modeling and tomography. However, you'll not be able to automatically differentiate (AD) through the code using any of the AD tools in the Python ecosystem, as the underlying implementation doesn't have any support for AD. You can, however, easily work with numerical differentiation, as long as you're willing to accept the shortcomings associated with it.

The acoustic propagation modeling in `UnderwaterAcoustics.jl` supports multiple backends. BELLHOP is one of the options, and so you can do whatever you'd be able to do with `arlpy` and BELLHOP, with `UnderwaterAcoustics.jl` and BELLHOP too. But we have a few other options too. For example, the `RaySolver` model in `UnderwaterAcoustics.jl` uses similar mathematics to that in BELLHOP, but is implemented fully in Julia. The advantage of this is that it is compatible with most of the AD tools in Julia, and so you get a differentiable propagation model. This may possibly be useful to you in some of your tomographic work.

On the flip side, the `RaySolver` model is not as mature as BELLHOP. However, that is easily mitigated by switching backends between `RaySolver` and BELLHOP and comparing results with the same code base, if there is any doubt about the results it produces. The `RaySolver` model is evolving (and slowly maturing) as we use it a fair bit in our work in my lab.

To address your question of Python vs Julia:

1. Acceptably, the Julia community is much smaller than the Julia community today. However, the community is sizeable and has an excellent set of packages publicly available. I find the community to be very dynamic, very helpful, and rapidly growing.
2. Algorithms written in Julia can provide excellent performance. On the other hand, in Python, you typically have to use underlying native C/C++/FORTRAN libraries for performance. This is fine if most of your compute load is linear algebra, etc, which is available as native code through `numpy` or the likes. However, if you have custom algorithms to be implemented, this can be a challenge. Solutions like `numba` partly address this, and so you can work around it in Python, if you prefer.
3. Personally, I find the ability to code in Julia and get performance without having to worry about workarounds very refreshing. I also like the design of the language, as it is very well suited to scientific computing. I have personally switched all my scientific computing to Julia over the past 18 months, and am very happy with the change. However, your mileage may vary, depending on your team's programming background and willingness to learn Julia.
3. Julia does have a good geospatial community (see https://github.com/JuliaGeo). For example, you mentioned NetCDF -- there is support for it (https://github.com/JuliaGeo/NetCDF.jl) and other formats in Julia. There is also great support in the community for saving data/models as CSV files, HDF5 files, BSON files, etc, and the [DataFrames.jl](https://dataframes.juliadata.org/stable/) package is very good for working with tabular data (like `pandas` in the Python ecosystem). You'd probably want to check some of these packages out before you make your language ecosystem decision.

I look forward to collaborating with you and your team members, no matter whether you choose to work in Julia or in Python. Most of my new work is in Julia, but I do still maintain the `arlpy` ecosystem, and work with several of my collaborators who still use Python.

**Comment by apatlpo** [comment]
Thank you very much @mchitre, this is precisely the kind of information I was looking for !

You did not mention solutions like calling julia from python (and passing information as arrays for example).
The python ecosystem not only offers versatile tools for environmental data representation and processing (pandas, xarray) but also very useful tools for distributed computed (see dask for hpc and cloud, more generally [pangeo](https://pangeo.io) effort). 
Having the best of both world would be ideal if we could call julia from python?
Is it a solution that you have investigated?
Do you know if it is viable?

**Comment by mchitre** [comment]
You can call Python from Julia very easily -- https://github.com/JuliaPy/PyCall.jl, so you can use the rich Python ecosystem even if you code in Julia. I have used this often, and works very well.

Julia has a [C/FORTRAN embedding API](https://docs.julialang.org/en/v1/manual/embedding/), so you can call Julia from C or FORTRAN. There is also [PyJulia](https://pyjulia.readthedocs.io/en/latest/usage.html) for calling Julia from Python, although I have not used it personally.

**Comment by apatlpo** [comment]
thanks again, it's time for discussion with my collaborators, now.
Hope to get back to you soon.
