### ISSUE TITLE
Absorption units

### ISSUE THREAD

**Issue by ElOceanografo** [org-arl/UnderwaterAcoustics.jl#54]
It's unclear from the documentation what units the result of the `absorption` function has. Is it just a loss ratio? 

I would find it useful to have a function that calculates the absorption coefficient in units of dB/m. Maybe this could be factored out of the current `absorption` function, or, at the very least, to have a description in the docstring for how to back this quantity out of the returned value...

**Comment by mchitre** [comment]
The absorption coefficient is simply a scale factor to the acoustic pressure to account for absorption. To get absorption in dB/m, simply compute it at 1 m range and convert to dB. Example:

```julia
plot(fkHz -> -20*log10(absorption(1000fkHz, 1)), 10, 100;
  xscale=:log10, yscale=:log10, xlims=(10, 100), ylims=(0.0001, 0.1),
  legend=false, xlabel="Frequency (kHz)", ylabel="Absorption (dB/m)")
```

<img width="599" alt="image" src="https://github.com/org-arl/UnderwaterAcoustics.jl/assets/3949878/9694624e-dec0-4328-b0b7-4d55aa7fd96f">

**Comment by ElOceanografo** [comment]
Thanks, that clarifies it. Could that info be added to the docstring?

**Comment by mchitre** [comment]
Thanks for the PR. Approved and will merge shortly.
